### ISSUE TITLE
[Reserved IP] WARNING no available reserved IPs for node 

### ISSUE THREAD

**Issue by MicheleSica** [Sh4d1/scaleway-k8s-node-coffee#12]
Hello,
After deployed the controller to a Kubernetes Kapsule cluster at Scaleway 
`kubectl create -f https://raw.githubusercontent.com/Sh4d1/scaleway-k8s-node-coffee/main/deploy.yaml`

set the secret
```
apiVersion: v1
stringData:
  SCW_ACCESS_KEY: XXXXXXXXXXX
  SCW_SECRET_KEY: XXXXXXXXXXX
  SCW_DEFAULT_ZONE: nl-ams-1
  SCW_DEFAULT_REGION: nl-ams
kind: Secret
metadata:
  name: scaleway-k8s-node-coffee
  namespace: scaleway-k8s-node-coffee
type: Opaque
```
set the configuration

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: scaleway-k8s-node-coffee
  namespace: scaleway-k8s-node-coffee
data:
  REVERSE_IP_DOMAIN: ""
  DATABASE_IDS: ""
  REDIS_IDS: ""
  RESERVED_IPS_POOL: "51.15.15.32"
  SECURITY_GROUP_IDS: ""
  RETRIES_NUMBER: "30"
```

Deployed a generic deployment that pointed to a node pool (with autoscaling on)
I got the below warning after the first node came up
`I0915 13:46:52.944681       1 reserved_ip.go:18] adding a reserved IP on node scw-t2-k8s-dev-pool-test-reservedip-c7c12842e8`
`W0915 13:46:53.241201       1 reserved_ip.go:60] no available reserved IPs for node scw-t2-k8s-dev-pool-test-reservedip-c7c12842e8
`

Checking the related code 
```
if err != nil {
		klog.Errorf("could not get a free IP for node %s: %v", nodeName, err)
		return err
	}

if ip == nil {
		klog.Warningf("no available reserved IPs for node %s", nodeName)
		return nil
	}
```
It seems that ip and err are `nil` because of 
```
ip, err := c.getFreeIP()
```

We know the result of the function getFreeIP() yet: `nil` `nil`
```
func (c *NodeController) getFreeIP() (*instance.IP, error) {
	instanceAPI := instance.NewAPI(c.scwClient)

	ipsList, err := instanceAPI.ListIPs(&instance.ListIPsRequest{}, scw.WithAllPages())
	if err != nil {
		return nil, err
	}

	for _, ip := range ipsList.IPs {
		if ip.Server == nil && stringInSlice(ip.Address.String(), c.reservedIPs) {
			return ip, nil
		}
	}
	return nil, nil
}
```
Therefore the following statement is always false
`ip.Server == nil && stringInSlice(ip.Address.String(), c.reservedIPs)`
Could you please help me on addressing the issue?
I really appreciate any help you can provide.

Best regards
Michele
